/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Akinator;

import static Akinator.VentanaCSV.hash_table;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;

/**
 * Clase VentanaPrincipal 
 * Ventana con las opciones para ir a la VentanaCSV y a la VentanaAkinator
 * @author sebas
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form VentanaPrincipal
     */
    public static ArbolBinario arb;
    public static archivoCsv csv;
    public static HashTable hash_table;
    /**
        * Constructor de VentanaPrincipal
        * @param hash_table estructura de datos Hash Table
        * @param arb estructura de datos Arbol Binario
        * @param csv archivo csv
        */
    public VentanaPrincipal(ArbolBinario arb,archivoCsv csv, HashTable hash_table) {
        initComponents();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.csv = csv;
        this.arb = arb;
        this.hash_table = hash_table; 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playButton = new javax.swing.JButton();
        dataBaseButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playButton.setBackground(new java.awt.Color(255, 102, 0));
        playButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        playButton.setForeground(new java.awt.Color(0, 0, 0));
        playButton.setText("EMPEZAR UNA PARTIDA");
        playButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        jPanel1.add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 190, 50));

        dataBaseButton.setBackground(new java.awt.Color(255, 102, 0));
        dataBaseButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        dataBaseButton.setForeground(new java.awt.Color(0, 0, 0));
        dataBaseButton.setText("BASE DE CONOCIMIENTOS");
        dataBaseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dataBaseButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dataBaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBaseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dataBaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 50));

        exitButton.setBackground(new java.awt.Color(255, 102, 0));
        exitButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("SALIR DEL JUEGO");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 40));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Animales");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Akinator");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Akinator/como-funciona-akinator-trucos-para-vencerlo-149177.jpg"))); // NOI18N
        jLabel1.setText("*IMAGEN*");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, 0, 780, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
        * Función playButtonActionPerformed
        * Permite moverse a la VentanaAkinator 
        */
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        if (arb != null) {
            this.dispose();
            VentanaAkinator ventanaAkinator = new VentanaAkinator(arb, hash_table);
        } else {
            JOptionPane.showMessageDialog(null, "Para jugar debe CARGAR o INICIALIZAR un archivo csv.\nPara hacerlo entre en 'BASE DE CONOCIMIENTOS'");
        }
    }//GEN-LAST:event_playButtonActionPerformed
    /**
        * Función dataBaseButtonActionPerformed
        * Permite moverse a la VentanaCSV 
        */
    private void dataBaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBaseButtonActionPerformed
        this.dispose();
        VentanaCSV ventanaCSV = new VentanaCSV(hash_table, arb, csv);
    }//GEN-LAST:event_dataBaseButtonActionPerformed
    /**
        * Función exitButtonActionPerformed
        * Finaliza el programa 
        */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int confirmacionSalir = JOptionPane.showConfirmDialog(null, "Deseas salir del juego?", "Respuesta", ConfirmationCallback.YES_NO_OPTION);
            if (confirmacionSalir == 0) {
                System.exit(0);  

        }else{
                return;
            }
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(arb, csv, hash_table).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dataBaseButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
