/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Akinator;

import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class VentanaCSV extends javax.swing.JFrame {
    public static HashTable hash_table;
    public static BinaryTree arb;
    public static archivoCsv csv;
    
    
    /**
     * Creates new form VentanaCSV
     */
    public VentanaCSV(HashTable hash_table, BinaryTree arb, archivoCsv csv) {
        initComponents();
        this.hash_table= hash_table;
        this.csv = csv;
        this.arb = arb;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        cargarButton = new javax.swing.JButton();
        inicializarButton = new javax.swing.JButton();
        consultarAnimalButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        mostrarBDCButton = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setEditable(false);
        pantalla.setColumns(20);
        pantalla.setRows(5);
        jScrollPane1.setViewportView(pantalla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 180, 270));

        backButton.setText("<<<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        exitButton.setText("x");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        cargarButton.setText("Cargar ");
        cargarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cargarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 20));

        inicializarButton.setText("Inicializar ");
        inicializarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicializarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(inicializarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, -1));

        consultarAnimalButton.setText("Consultar Animal");
        consultarAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAnimalButtonActionPerformed(evt);
            }
        });
        jPanel1.add(consultarAnimalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 220, 30));

        guardarButton.setText("Guardar ");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(guardarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, 20));

        mostrarBDCButton.setText("Mostrar Base de Conocimientos");
        mostrarBDCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarBDCButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mostrarBDCButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 220, 30));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(" *NOTA: Recuerde que al cargar un \n archivo, este debe ser de tipo \"csv\".");
        jPanel1.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 40));

        jButton1.setText("Guardar en archivo por defecto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 20));

        jButton2.setText("Cargar archivo por defecto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        new VentanaPrincipal(arb, csv, hash_table);
    }//GEN-LAST:event_backButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void consultarAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAnimalButtonActionPerformed
        // TODO add your handling code here:
        String cadena= JOptionPane.showInputDialog("Ingrese el nombre del animal a buscar: ");
        boolean es_numero= cadena.matches("[+-]?\\d*(\\.\\d+)?");
        if (es_numero || cadena.isBlank() || cadena.isEmpty() || cadena==null) {
            pantalla.setText("La cadena no puede ser numérica o estar vacía");
            return;
        }
        Nodo buscado= hash_table.buscar(cadena);
        if (buscado==null) {
            pantalla.setText("El animal no se encuentra registado");
            return;
        }
        
        
        pantalla.setText("El animal " + buscado.getInfo()+" Se encuentra registrado");
    }//GEN-LAST:event_consultarAnimalButtonActionPerformed

    private void cargarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarButtonActionPerformed
        this.csv = new archivoCsv();
        this.arb = new BinaryTree();
        this.hash_table= new HashTable(10111);
        csv.abrirArchivo(arb, hash_table);
    }//GEN-LAST:event_cargarButtonActionPerformed

    private void inicializarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicializarButtonActionPerformed
    if (arb == null && hash_table == null) {
            JOptionPane.showMessageDialog(null, "Su base de conocimientos ya esta vacia.");
        } else {
            arb = null;
            hash_table = null;
            JOptionPane.showMessageDialog(null, "Su Base de Conocimeintos fue inicializada correctamente");
        }
    }//GEN-LAST:event_inicializarButtonActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        archivoCsv csvAux = new archivoCsv();
        if (arb == null && hash_table == null) {
            JOptionPane.showMessageDialog(null, "Su arbol se encuentra vacio");
        } else {
            String cadena="Pregunta, No, Si"+"\n";
            cadena=arb.archivorder(arb.getRoot(), cadena);
            csvAux.guardarArchivo(cadena);
        }

    }//GEN-LAST:event_guardarButtonActionPerformed

    private void mostrarBDCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarBDCButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarBDCButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        archivoCsv csvAux = new archivoCsv();
        if (arb == null && hash_table == null) {
            JOptionPane.showMessageDialog(null, "Su arbol se encuentra vacio");
        } else {
            String cadena="Pregunta, No, Si"+"\n";
            cadena=arb.archivorder(arb.getRoot(), cadena);
            csvAux.escribirCvsPorDefecto(cadena);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.csv = new archivoCsv();
        this.arb = new BinaryTree();
        this.hash_table= new HashTable(10111);
        csv.leerPorDefecto(arb, hash_table);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCSV(hash_table, arb, csv).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton cargarButton;
    private javax.swing.JButton consultarAnimalButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JButton inicializarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mostrarBDCButton;
    private javax.swing.JTextArea pantalla;
    // End of variables declaration//GEN-END:variables
}
